### ISSUE TITLE
Clash/Advance Map Updates

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#1036]
**Task List:**
- [ ] Add engineer roles or fix them (so they have primary weapon)
- [ ] Add Objectives Spawns
- [ ] Fix vehicle pool so it doesn't say "32" tanks/vehicles max

**Maps updated:**
- [ ] Barashka_Clash
- [ ] Bridgehead_Advance
- [ ] Caen_Advance
- [ ] Cambes
- [ ] Carpiquet
- [ ] Cheneux_Advance (Update balance at same time)
- [x] Hattert Clash
- [x] Hedgerow Hell Clash
- [ ] La Cambe
- [ ] La Gleize Advance
- [ ] Lutremange Clash
- [ ] Noville Advance
- [ ] Nuenen Clash
- [ ] Oosterbeek Advance
- [x] Putot en Bessin Advance
- [ ] Radar Advance
- [ ] Salaca Clash
- [ ] Stoumont Advance
- [ ] Varaville Advance
- [x] Berezina Advance
- [ ] Black Day July Advance
- [ ] Butovo Advance
- [x] Champs Advance
- [x] Cholm Advance
- [ ] Dom-Pavlova Advance
- [ ] Kasserine Pass Advance
- [ ] Klin1941 Advance
- [ ] Kriegstadt Advance
- [ ] Leszinow Advance
- [ ] Makhnovo Advance
- [ ] Merderet Advance
- [x] Myshkova River Advance
- [ ] Ogledow Clash
- [ ] Pegasus Bridge Advance
- [ ] Poteau Ambush Advance
- [ ] Rhine River Clash
- [ ] San Valentino Advance
- [ ] Schijndel Advance
- [ ] Smolensk Advance
- [ ] Valko Advance
- [ ] Winter Stalemate Clash (?)
