### ISSUE TITLE
Artillery Overhaul

### ISSUE THREAD

**Issue by shiftycats** [DarklightGames/DarkestHour#1074]
### Rules:
* Squad leader takes the role of the observer.
* Depending on how artillery units receive targets, they can be divided into squad assets (mortars) and team assets (artillery vehicles and guns). An artillery piece can get targets from:
    * Only it's own squad leader (for squad assets)
    _\+ Keep it simple
    \+ Player is focused on the task at hand
    \-  Required to be in a squad to receive targets_
    * All squad leaders (for team assets)
    _\+ Versatile; no requirements; player has choices
    \- Some requests from squad leaders will be left unfulfilled
    \- Lots of confusing markers with no context on the overhead map_
* Squad leader can only see hit locations from a squad asset.
* Observer features are disabled for squad leaders rocking a mortar class (which should not be allowed in the first place).

### Tasks:
- [x] Rework the system that reports hit locations on the map.
- [x] Add new fire support marker.
- [x] Add actions for marking targets to the command menu (including off-map artillery and airstrikes).
- [x] Change the hit icon.
- [x] Deprecate the artillery observer class.
- [x] Allow artillery operators to view their kill feed (even when server-wide kill feeds are disabled)
- [x] Long-range artillery pieces should have numeric readout of pitch/yaw of the primary cannon
    - [x] M7 Priest
    - [x] LeIG18
    - [x] Axis mortar
    - [x] Allied mortar
- [x] Display range table for all artillery pieces
    - [x] M7 Priest
    - [x] LeIG18
    - [x] Axis mortar
    - [x] Allied mortar
- [x] Add spotting scope for all artillery piecies as a third position (new DriverPosition)
    - [x] M7 Priest
    - [x] LeIG18
    - [x] Axis mortar
    - [x] Allied mortar
- [x] replace temporary hit markers with new textures

**Comment by DeadlyDad** [comment]
This was suggested shortly after mortars were introduced and a number of us talked at length about it.  Some improvements that were discussed:

As a real-world mortar round spends a **LOT** of time in the air relative to horizontal distance travelled, a number of factors can affect where it will land, including wind speed and direction, altitude difference between mortar and target, air pressure, humidity, etc.  Put together, it is clear that even a trained mortar team IRL has to adjust its aim based upon the dynamic conditions of the atmosphere above the battlefield.  Both to simulate realistic firing conditions and to stop players from gaming the system, a few variables were suggested to change flight path characteristics:
- Wind speed & direction: a force vector pointing in the direction of the wind with an amplitude based on wind speed is added to the projectile during flight, causing it to veer from its intended path.  (Both speed and direction slowly change over the course of the match, ranging around a main speed and direction, and so the vector needs to be calculated each firing.)  
- Atmospheric conditions: An average effect is decided for each, then the various effects are compiled into a multiplier which is used on the projectile's velocity during flight, causing it to travel faster or slower than the average.  This only needs to be calculated at the beginning of the round.

In-game, mortarmen should be able to mark on the map where they want their shells to land and an ellipse drawn on the map showing where they are (theoretically) expected to land.  (The pattern IRL is an ellipse, not a circle, according to the US military field manuals I studied.)  The direction and inclination of the mortar to (theoretically) hit that target are then automatically presented in the HUD for the mortarman to dial in manually.  In order to know where they actually *are* landing, however, an observer (someone with binoculars) must be watching them land.  Every time one does, the average position and coverage of the hits are overlayed on the map in another colour and a new direction and inclination is presented on the HUD under the current ones.  This will allow the mortarman to adjust his aim by selecting the observer's data instead of his own estimates.  This simulates how an actual, fully-trained mortar team operates in real life, where all calculations are done before a single wheel is turned.  (The direction and inclination can still always be adjusted manually outside of the calculations.)

This same system would work for other indirect fire weapons.

Does that make sense?

**Comment by mimiski** [comment]
Motivation of the latest changes:
![motivation](https://user-images.githubusercontent.com/56321463/77211705-10422400-6b05-11ea-9ba8-10be85e72d87.png)
Image 1. shows how it used to be prior to 9b7b875a5aaf9e729a52f12dfc381716eff44593: a marker with `bSquadSpecific=true` was  visible to each squad member and nobody else.
Image 2, shows a situation which had not been achievable before, namely to have a per-squad marker visible to players outside of the squad. Possible scenario: SL of squad 1. marks an artillery target with Marker 1., mortar operator (member 2. of squad 2.) and Priest crewman (member 2. of squad 3.) see Marker 1. and can coordinate fire. Moreover, all squad members of squad 2. see Marker 2. but only a subset of members of squad 3. see Marker 3. All markers (1., 2., 3.) have `bIsSquadSpecific=true`.

**Comment by mimiski** [comment]
Range tables for Priest and LeIG18 were implemented in  d8fcbd9a23a6ec152b81e5827f0e165ebe8e30a1

**Comment by cmbasnett** [comment]
![image](https://user-images.githubusercontent.com/5035660/93522558-8540bb80-f8e6-11ea-8103-cf8dc4c67394.png)
I would suggest coming up with some sort of solution for how to make this table less long. Some ideas:

* Less entries in the table (less accuracy but would be easier to read the table)
* Add another column (might reduce readability)
* Somehow let the user scroll the table

**Comment by shiftycats** [comment]
It'd be wise to shorten the table by only displaying lines in 50 meter increments. The pitch values can be interpolated (and rounded if needed).

**Comment by mimiski** [comment]
> It'd be wise to shorten the table by only displaying lines in 50 meter increments. The pitch values can be interpolated (and rounded if needed).

Fixed in 33b49519031018e095d31f0830b1b85a0bde0508.
