### ISSUE TITLE
Objective Spawns

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#973]
Objective Spawns are a spawn-point which are dynamically generated each time an objective is secured. The idea is for each team to have a secured spawn point closer to the battlefield in the case Rally Points go down and the only choice is to spawn at Main. 

The requirements for an Objective to have an Objective Spawn for your team to be present is:
1.  It must be controlled by your team
2.  It must be inactive (secured), but attached/linked to an active objective
3.  It must have a hint tag defined in the objective variables

If an objective which qualifies for the first two requirements, but not the third exists the system will look for the next one that does (using a tree node).

This feature is mainly intended to be used for Clash, but depending on its success, can be installed for Advance maps as well.

**Tasks:**

- [x] Create separate icon to indicate an objective spawn

- [x] Has a longer spawn timer (try +20 seconds by default)

- [x] Add support in the objective class

- [x] Implement dynamic generation/deletion of Objective Spawns

- [x] Handle setup phase

**Comment by cmbasnett** [comment]
Separate hints would be possible and easy to do. By default, the location hints could just be neutral.

And yes, we can just have it traverse the objective tree until it finds one with a reserve spawn.

**Comment by AndrewTheel** [comment]
This feature is completed and additional work or bugs will need separate issues reported.
