### ISSUE TITLE
Server Browser and Replication Updates

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#990]
**Tasks:**
- [x] Add a column for server version number, grey out servers that are not the same version as the client
- [x] Add a column for server performance, will have a 1-5 state climbing graph icon with colors (red to yellow)
- [ ] Remove unused or useless "rules" for a selected server, as that area is way to busy and not useful
- [x] Add option for putting the server name on the scoreboard!

**Ideas:**
For the performance indicator, we could have servers report/replicate the average tick, if below 20 the server browser would not consider it max, 10 should be the poorest value.
Add flag for the country the server is located in or have a separate column for its indication?
Add a recommended column, servers with stars are recommended?

**Comment by AndrewTheel** [comment]
- [ ] Make it so the server stores the location in a DP (not config variable) and only have it do the location http request each time it starts up

**Comment by AndrewTheel** [comment]
This is on hold until the HTTP problem is resolved.

**Comment by AndrewTheel** [comment]
Closing as not a priority and once we implement a backup "server-list" for when steam servers are down, a new issue will be tracked for that.
