### ISSUE TITLE
Server Performance Regulation System

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#991]
**Tasks:**
- [ ] Reduce the added respawn times for strikes or even remove
- [ ] Give a bit more time before a strike is given
- [ ] Make the poor performance messages less annoying
- [ ] Should report via metrics the level, how many players, active objective(s), etc to help us detect levels with problematic areas which hurt server tick
- [ ] Add an array of recommended server IPs in the script, avoid doing online (somewhere)
- [ ] If a server strikes out, it shouldn't start a MidGameVote immediately. Instead it should start a server wide vote to either A) Travel to the recommended server (Server Name / IP), B) Start a mid game vote, or C) Continue playing the level with 2 minute respawn times
